name: Scheduled Empty Commit (Monthly)

on:
  schedule:
    - cron: '*/5 * * * *'  # Cada 5 minutos # '0 0 1 * *'  # Día 1 de cada mes a las 00:00 UTC
  workflow_dispatch:  # Permite correrlo manualmente

permissions:
  contents: write  # Esto es CLAVE para permitir push

jobs:
  empty-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "Automated Commit Bot"
          git config user.email "bot@example.com"

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "Monthly automated empty commit to keep workflows active"

      - name: Push commit using GH_PAT
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD
