name: Run Email Worker

on:
  workflow_dispatch: # Allows manual runs
  schedule:
    - cron: '0,30 * * * *' # Runs every hour at :00 and :30

jobs:
  process-queue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Use the version of Node.js you need

    - name: Install Dependencies
      run: npm install

    - name: Run Worker
      env:
        REDIS: ${{ secrets.REDIS }}
      run: node processes/email.process.js
